### ISSUE TITLE
How to Exec Commands System

### ISSUE THREAD

**Issue by amartinr1977** [nwutils/nw-vue-cli-example#1]
Hello!! I am trying to make system calls and execute commands from the nwjs application using its boilerplate but I can't. Without making use of Vue-cli3 / Webpack / Babel it works, but don't compile the code from vue-cli3.

As an example, so far, when I want to execute a system command to know the user who has started a graphic session, did something similar to the following:

```
// To execute commands asynchronously:
const util = require ("util");
const miexec = util.promisify (require ("child_process"). exec);
```

```
// Then in a vue mixin or from a vuex action I ran the following from a function:
command = "whoami"
try {
        const res = await miexec (command)
        if (res.stderr) {
          console.error (`Error with $ {command}: $ {res.stderr}`);
          return null
        }
        message = `Ok !! => $ {res.stdout.toString ()} `
        console.log (message);
        return res.stdout.toString ()
      } catch (err) {
        message = "Error:" + result.stdout.toString ()
        console.log (message)
        return "error"
      }

```
The problem I find is that he does not like the initial **require**, or does not know what I am referring to:

const util = require ("util"); ????

Would you know how to solve the previous problem?
Thank you very much in advance. Regards

**Comment by amartinr1977** [comment]
Hello again,

I already have the solution. As you indicate through the code it is possible to refer to everything related to nw through window.nw. In this way the code could be as follows:

```
export const mymixin = {
  methods: {
    async myexec(comando) {
      let mensaje = "=> Se va a ejecutar Asincronamente el comando: " + comando;
      console.log(mensaje)
      // Constantes que usaremos en toda la aplicación:
      // Para ejecutar comandos del sistema en modo asíncrono:
      let util = window.nw.require("util");
      let miexec = util.promisify(window.nw.require("child_process").exec);
      try {
        const resultado = await miexec(comando)
        if (resultado.stderr) {
          console.error(`Error al ejecutar ${comando}: ${resultado.stderr}`);
          return null
        }
        mensaje = `Ok!! Resultado de ejecutar: ${comando} => ${resultado.stdout.toString()}`
        console.log(mensaje);
        return resultado.stdout.toString().trim()
      } catch (err) {
        mensaje = "Resultado de Ejecución: Error - Problemas => " + comando + " => " + resultado.stdout.toString()
        console.log(mensaje)
        return "EEeeerror"
      }
    },
    mostrarinfo() {
      console.log("Esto funciona .... desde el mixin ...")
    }
  }
}

```

Thank you very much for your work and your dedication to Vue and NWjs, which helps us a lot to other people in other parts of the world. Thank you!!

**Comment by TheJaredWilcurt** [comment]
Because Vue does a lot of "magic" inside the Object, there are some limitations. For example a method must be a function and not an arrow function, and access to global values must be referenced starting with the `window` object.

So `window.require` or `window.nw.require` (slightly safer) is needed in your Vue components. Same with `window.process` or `window.nw.process`.
