### ISSUE TITLE
Blank screen of white in production

### ISSUE THREAD

**Issue by bonniss** [nwutils/nw-vue-cli-example#12]
Hello guys, I have used this boilerplate to make an experiment app on Windows 10 x64. I ran `npm run build:win`, and the output distribution works on my machine (developer's machine). Then I sent the `.zip` version to other laptops, unzip and run the `.exe`, it surprisingly shows a blank screen of white. I could not figure out how to debug that situation, I therefore remade the app step by step and built after every step.

The result is it always works on my machine, and but not on others' if I import anything into the Vue components' `script`.

```js
import { C_DATE, formatDate } from '@/utils/date';
import { logger } from '../utils/log';

export default {
  data() {
    return {
      dateTitle: formatDate(window.dayjs(), C_DATE.FM_YYYYMMDD_FULL),
      msg: window._getTerm('system_msg.fetch_future'),
    };
  },
  created() {
    logger.info('Đang khởi tạo trang chủ');
  }
};
/**
 * => Output normally on developer's machine
 * => Output a blank screen of white on machines with the same environment, without Node installed
 */
```

Any thoughts?

**Comment by gwasserfall** [comment]
Can you enable console and check if there are any errors on the machines that are blank?

**Comment by TheJaredWilcurt** [comment]
Not able to reproduce. No response about errors. Closing.
