### ISSUE TITLE
Setting up E2E testing

### ISSUE THREAD

**Issue by haohaodehao** [nwutils/nw-vue-cli-example#2]
when I run e2e test task and i get this message
![捕获2](https://user-images.githubusercontent.com/38996126/66795481-516f5000-ef37-11e9-94b2-312c091810e2.PNG)
it look like my chrome version is not in 71 -- 75. that should use nw.exe . but it use my desktop chrome software. my desktop chrome version is  77.0.3865.120.

then i uninstall my desktop chrome and run e2e test task. and i get this message
![捕获](https://user-images.githubusercontent.com/38996126/66795630-c3e03000-ef37-11e9-8c7d-b0863c73b8a8.PNG)
that say cannot find chrome binary.

so why has this error?

**Comment by TheJaredWilcurt** [comment]
Read the README

**Comment by TheJaredWilcurt** [comment]
I have not been able to get E2E testing set up for this repo. It will require using the NW.js Chrome Driver:

* http://docs.nwjs.io/en/latest/For%20Users/Advanced/Test%20with%20ChromeDriver/

* https://github.com/cypress-io/cypress/issues/4662

**Comment by haohaodehao** [comment]
O, thanks. i think i should try python selenium. use nwJs official way.
