### ISSUE TITLE
Exclude or Ignore some directories or files from the build

### ISSUE THREAD

**Issue by Xsmael** [nwutils/nw-vue-cli-example#39]
Hello, 

Is there a way to ignore some files or directories from the build ?  i have a case where i need this kind of feature, that'll be quite handy, otherwiser, we have to do it manually everytime we build, but we need the files back, for development.

Thanks!

**Comment by TheJaredWilcurt** [comment]
Automated build uses `nwjs-builder-phoenix`. It's options are here:

* https://github.com/evshiron/nwjs-builder-phoenix/blob/master/docs/Options.md

**Comment by Xsmael** [comment]
Thanks! that works for me, also I noticed in package.json there is  a properter excludeFiles, that holds and array of paths to exclude.
