### ISSUE TITLE
vue and nw.   os.platform question

### ISSUE THREAD

**Issue by bulolo** [nwutils/nw-vue-cli-example#9]
os.platform()
return  "browser"

not macOs? or window?

how to return platform of system

**Comment by TheJaredWilcurt** [comment]
Depending on where you call the code from:

* `process.platform`
* `window.nw.process.platform` - sometimes this level of specificity is required based on how Vue manipulates context

`process.platform` will return:

* `linux`
* `win32` for Windows (32 or 64-bit, use `process.arch` to see which)
* `darwin` for OSX

**Comment by bulolo** [comment]
![image](https://user-images.githubusercontent.com/10026498/80060958-74239680-8562-11ea-8534-423a350365c1.png)

return "browser"

**Comment by TheJaredWilcurt** [comment]
As mentioned previously, you need to do the full shebang because Vue messes with the JS context.
```js
  computed: {
    platform: function () {
      return window.nw.process.platform;
    }
  }
```
